swagger: "2.0"
info:
  description: describe route controllers for people Api
  version: "1.0.0"
  title: Python ReST People Api
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths opened
paths:
  
  /profile:
    # route to get all profiles
    get:
      operationId: people.read_all
      tags:
        - People
      summary: Read the entire list of people
      description: Read the list of people
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of people to get from people
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                useranme:
                  type: string
                age:
                  type: integer
                id:
                  type: integer

  
  /profile/new:
    # route to create a new profile
    post:
      operationId: people.create
      tags:
        - people
      summary: Create the Profile entity with the fields described
      description: Create a new profile in the people list
      parameters:
        - name: profile
          in: body
          description: profile to create
          required: True
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First name of profile to create
              last_name:
                type: string
                description: Last name of profile to create
              useranme:
                  type: string
                  description: Unique username of the profile to create
              age:
                type: integer
                description: Age of the profile to create
              id:
                type: integer
                description: Unique id of the profile to create
      responses:
        201:
          description: Successfully created profile in list

  /profile/{id}:
    # route to get a profile through its id
    get:
      operationId: people.read_one
      tags:
        - people
      summary: Read one profile from the people list
      description: Read one profile from the people list
      parameters:
        - name: id
          in: path
          description: id of the profile to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read profile from people list operation
          schema:
            properties:
              first_name:
                type: string
              last_name:
                type: string
              useranme:
                type: string
              age:
                type: integer
              id:
                type: integer

  /profile/update:
    # route to update a profile's username and/or age
    put:
      operationId: people.update
      tags:
        - people
      summary: Update a profile in the people list
      description: Update a profile in the people list
      parameters:
        - name: profile
          in: body
          required: True
          description: profile to update in the list
          schema:
            type: object
            properties:
              username:
                type: string
              age:
                type: integer
              id:
                type: integer
      responses:
        200:
          description: Successfully updated profile in people list
              
  /profile/remove/{id}:
    # route to remove a profile
    delete:
      operationId: people.delete
      tags:
        - people
      summary: delete a profile in the people list
      description: delete a profile in the people list
      parameters:
        - name: id
          in: path
          required: True
          description: id of profile to delete from the list
          type: integer
      responses:
        200:
          description: Successfully deleted profile in people list